# Generated by Django 4.2.1 on 2023-05-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_booking_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='remarks',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Cancelled by student', 'Cancelled by student'), ('Cancelled by counsellor', 'Cancelled by counsellor'), ('Completed', 'Completed'), ('Missed by student', 'Missed by student'), ('Cancelled due to Institute holiday', 'Cancelled due to Institute holiday'), ('Counsellor on leave', 'Counsellor on leave')], default='Pending', max_length=40),
        ),
    ]
