# Generated by Django 4.2.1 on 2023-05-31 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0009_availableslot_unique_slot'),
        ('users', '0003_alter_booking_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='slot',
            field=models.ForeignKey(limit_choices_to={'isAvailable': True}, on_delete=django.db.models.deletion.CASCADE, to='slots.availableslot'),
        ),
    ]
