# Generated by Django 4.2.1 on 2023-05-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
