# Generated by Django 4.2.1 on 2023-05-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0005_alter_leave_counsellor'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='holiday',
            constraint=models.UniqueConstraint(fields=('date',), name='unique_holiday'),
        ),
    ]
