# Generated by Django 4.2.2 on 2023-06-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='token',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
