# Generated by Django 4.2.2 on 2023-06-06 14:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_booking_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
