# Generated by Django 4.2.1 on 2023-05-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0003_holiday_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
