# Generated by Django 4.2.1 on 2023-05-29 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('slots', '0004_leave_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='counsellor',
            field=models.ForeignKey(limit_choices_to={'is_ticc_counsellor': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
