# Generated by Django 4.2.1 on 2023-05-30 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0007_availableslot_capacity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='start_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='end_date',
        ),
    ]
