# Generated by Django 4.2.1 on 2023-05-31 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0008_rename_start_date_leave_date_remove_leave_end_date'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='availableslot',
            constraint=models.UniqueConstraint(fields=('date', 'start_time'), name='unique_slot'),
        ),
    ]
